version: '3.0'

services:

  postgres-test:
    image: postgres:latest
    ports:
      - 6543:5432
    env_file: postgres.env
    networks:
      - baeldung

networks:
  baeldung:
    driver: bridge
